function() {
    try {
        throw 'Exception';
    } catch (e) {
        debugger;
    }
}